create table tasks (
    id int primary key generated by default as identity,
    name varchar(128) not null,
    description varchar,
    status varchar(64) not null,
    created_at timestamp not null,
    updated_at timestamp,
    user_id int references users(id) not null
);